### ISSUE TITLE
Blocking Cookies will cause the Page to Hang on Loading.

### ISSUE THREAD

**Issue by safelock** [nicolaschan/bell#106]
Title.

**Reproduce Instructions**: Block All (including Third-Party) Cookies on Chrome or Firefox, and attempt to load the site. 

2 Errors are thrown in the JS console, which are listed below.

One is: `Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://bell.plus/') with script ('https://bell.plus/bin/service-worker.js'): The user denied permission to use Service Worker.`

The other is: `client-mithril.js:formatted:11073 Uncaught (in promise) Error: No available storage method found.
    at n (client-mithril.js:formatted:11073:53)`

It appears that some exception handling is required for these items since the site can still work (and reports ready in the JS Console) without these items, it just means that user data will not store locally and will be unavailable after a refresh of the site.

This "no storage effect" does not affect users who just use one of the built-in schedules, as they can still continue to use a direct link to the schedule to load their preferred schedule, or the root site to load the default schedule (LAHS on bell.plus). They will however, still hang due to the exception handling not being properly implemented.

**Workaround**: Please enable (at the very min) First Party Cookies and Local Storage. These are only stored within your browser and contain data about your schedules should you decide to store a custom schedule. You may clear these at any time, with the only caveat being that if you clear the local storage, you also clear any custom schedule you may have entered, and will need to re-enter that schedule again.

**Comment by nicolaschan** [comment]
Thanks for reporting! Resolved by handling service worker registration error and using an in-memory fallback for localForage. Changes have been deployed in prod. Feel free to reopen if this continues to be an issue.
