### ISSUE TITLE
egan bell not right

### ISSUE THREAD

**Issue by Hedgehawk11** [nicolaschan/bell#109]
my chum goes to egan and the bell schedule is off, here is the correct schedule for Friday/Tuesday

![image](https://user-images.githubusercontent.com/84346970/201995522-0b025bce-6663-40c7-b2eb-e6d1abefa284.png)

hope this helps

EDIT: advisory on wednesday is tutorial too got email from him

**Comment by nicolaschan** [comment]
LGTM!
