### ISSUE TITLE
Shared schedules are broken

### ISSUE THREAD

**Issue by gogo6211** [nicolaschan/bell#117]
When going to the settings page or just bell.plus the shared schedule disappears and can only be accessed through the URL. [Screen recording 2024-08-22 8.53.46 AM.webm](https://github.com/user-attachments/assets/2fbf16c1-31e1-4092-a0a3-b0eec69257d1)

**Comment by nicolaschan** [comment]
Thanks for the report! This is intended behavior for now to prevent spam from the list. I can manually add a school to the list if you'd like.

**Comment by gogo6211** [comment]
Just wanted to add that it works now as it did before edit.bell.plus went down for a short period. For a few days after edit.bell.plus come back online this issue described above was happening. If you go to the settings page while on a shared schedule to change a setting/theme and go back, you stay on the shared schedule. 🎉

**Comment by gogo6211** [comment]
Just wanted to add that it works now as it did before edit.bell.plus went down for a short period. For a few days after edit.bell.plus come back online this issue described above was happening. If you go to the settings page while on a shared schedule to change a setting/theme and go back, you stay on the shared schedule. 🎉

**Comment by nicolaschan** [comment]
Ah thanks for clarifying! I didn't realize this also applied to changing a setting like the theme. Thanks for the report and I'm glad it's working now!
