### ISSUE TITLE
edit.bell.plus down

### ISSUE THREAD

**Issue by gogo6211** [nicolaschan/bell#119]
edit.bell.plus is down again :(

**Comment by nicolaschan** [comment]
Sorry about that! I'll look into it. I really need to set up better alerting. Thanks for the report!

**Comment by nicolaschan** [comment]
Should be back now. I couldn't find anything conclusive, the machine was powered on but not responsive. Maybe some CPU or memory instability. I tweaked the bios settings and will continue monitoring. Thanks again for raising it!
