### ISSUE TITLE
Changing color with gradient theme doesn't transition

### ISSUE THREAD

**Issue by MistriHD** [nicolaschan/bell#14]
It used to transition from one color to another very smoothly, but there is now no transition with the new gradient theme. Can you add one?

**Comment by nicolaschan** [comment]
Yes, this is an issue. Unfortunately, fading gradients is much more complicated than fading solid colors. I have two solutions in mind.
1) A pure JavaScript version (no css transitions) to set the color
2) Have two layers and slowly fade out the top layer to reveal the next gradient below

**Comment by nicolaschan** [comment]
Fixed! The background is now made up of two layers. The top layer fades in or out when they need to be updated.
