### ISSUE TITLE
Synchronizing window sometimes gets stuck

### ISSUE THREAD

**Issue by arjunpat** [nicolaschan/bell#17]
The synchronizing spinner/loader just got stuck and reloading doesn't fix it. Here is the console:

20:04:40 INFO: Type `logger.setLevel('debug')` to enable debug logging
client.js:50237 Uncaught (in promise) TypeError: this.setBellCompensation is not a function
    at BellTimer.loadCustomCourses (client.js:50237)
    at BellTimer.reloadData (client.js:50237)
    at BellTimer.initialize (client.js:50240)
    at client.js:49663
    at <anonymous>
![screen shot 2017-11-12 at 8 04 57 pm](https://user-images.githubusercontent.com/29242551/32709393-f62338d6-c7e4-11e7-96d8-aff4f9bb39c8.png)

**Comment by arjunpat** [comment]
The problem was fixed after clearing all site data — possibly a caching problem.

**Comment by nicolaschan** [comment]
Did you have custom courses enabled or were you using LAHS?

**Comment by nicolaschan** [comment]
Was able to reproduce by choosing "Custom" as the school and not entering any schedules.

**Comment by nicolaschan** [comment]
Fixed! Thank you so much for reporting this. Please reopen the issue if this happens again or is not fixed it all cases.
