### ISSUE TITLE
no website caching

### ISSUE THREAD

**Issue by arjunpat** [nicolaschan/bell#20]
Hi!

As a fellow website developer, I noticed that recently your website doesn't cache resources such as JS and CSS.
This is especially concerning as your download per page-load has come up to 41.9 KB compared to the ~5 KB it was before.
**Update:** I just noticed that it is about 50 KB on Google Chrome because of "304 Not Modified" headers. However, on browsers that don't fully support that, I get around 500 KB of information downloaded on each page load.

I know you may have done this purposefully, but I think that it greatly increases load time.

On top of that is server load:
You're are running node.js on a home server (I assume Comcast because of an IP lookup).
At the amount of page loads you get, you have the possibility of overloading your server and your home bandwidth.
You used to use Cloudflare which seems like a great way to ensure protection and speed of your website, but it seems like that was also recently disabled.

I realize that you might have done this all for a reason; as a curious fellow developer, would you mind enlightening as to the benefits of these changes?

**Comment by nicolaschan** [comment]
Hi arjunpat! Thanks for sharing your concerns.

> As a fellow website developer, I noticed that recently your website doesn't cache resources such as JS and CSS.

I update the code frequently and I want to make sure everyone is always using the latest version. Which browsers don't support 304 Not Modified? I'm in the process of testing service workers for offline caching, and it should be ready within the next week.

> You're are running node.js on a home server (I assume Comcast because of an IP lookup). 
At the amount of page loads you get, you have the possibility of overloading your server and your home bandwidth.

It's behind an ngnix reverse proxy which provides much better performance than node.js. We have a tomcat backend in the works on the `server` branch.

> You used to use Cloudflare which seems like a great way to ensure protection and speed of your website, but it seems like that was also recently disabled.

Privacy concerns. I want to be able to use my own certificates and do not want Cloudflare to collect analytics.

Have you ever experienced problems loading the website?

**Comment by arjunpat** [comment]
Cool! I just wanted to let you know in case you didn’t purposefully do anything.

In terms of 304 Not Modified, I had a little trouble with Opera and Firefox as they didn’t provide consistent results.

Have you thought about writing a few lines of code that automatically adds a GET version request in the js and css. ex: main.js?v=2.4.1
It’s never bad to reduce server requests.

In terms of Cloudflare security: I always have relied on cloudflare for home servers because I wanted to hide my IP address to prevent DDOS, etc. to my family’s home network. Are you worried about people’s ability to easily lookup your home ip?

**Comment by nicolaschan** [comment]
> In terms of 304 Not Modified, I had a little trouble with Opera and Firefox as they didn’t provide consistent results.

Can you elaborate on what you mean when you say they didn't provide consistent results? Would they fetch the resource anyway? If this is true, perhaps you should bring this to the attention of the developers of Opera and Firefox.

> Have you thought about writing a few lines of code that automatically adds a GET version request in the js and css. ex: main.js?v=2.4.1

I used to do this but I decided I don't want to have server side rendering. I suppose I could manually add it, but this won't matter once the service worker is ready. It simply sends the exact same HTML file to every user, and nginx takes care of static files like that. Node doesn't have to render `index.html` since it is static.

> In terms of Cloudflare security: I always have relied on cloudflare for home servers because I wanted to hide my IP address to prevent DDOS, etc. to my family’s home network. Are you worried about people’s ability to easily lookup your home ip?

My IP is already exposed for hosting other servers, so it's already out there. As far as I know, Cloudflare only proxies websites, not other servers. This still doesn't address my privacy concern with Cloudflare.

Thanks for your concern. Let me know if you have any more questions.

**Comment by nicolaschan** [comment]
Offline support has been added in v3.1.2. If you have any more suggestions related to this issue, feel free to reopen it.
