### ISSUE TITLE
Allow iOS users to add to homescreen as standalone app

### ISSUE THREAD

**Issue by JamsheedMistri** [nicolaschan/bell#38]
If you have an iOS device, most people are unaware that it's super easy to make a native app out of a normal website for easy access.

In Safari, there's an option to export a website to the homescreen. Once you do that, it sets the current page `<title>` to the title of the app, and the current page render as the app icon. When you click the app, it just opens Safari to the saved webpage.

However, Apple allows you to customize this using `<meta>` tags, and it's actually really neat!

I'd propose adding these meta tags (I would make a PR myself but I'm not sure where they're supposed to go).

```
<meta name="apple-mobile-web-app-title" content="bell">
```
This would make the name of the web app "bell" rather than the current time (as the tablist would display normally) when exporting.

```
<meta name="apple-mobile-web-app-capable" content="yes" />
```
This will make the app able to be exported as its own standalone app. Meaning that when you open it, it'll open in its own app rather than in Safari.

```
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
```
This will allow the top status bar to blend in with the app

```
<link rel="apple-touch-icon-precomposed" href="assets/images/logo.png" />
<link rel="apple-touch-icon" href="assets/images/logo.png" />
```
If linked to the correct location, this will change the app icon to whatever the image is. Must be a square. I'd recommend using the current logo we have for our Twitter. I made a special one for this purpose, you can find it at this link: https://i.imgur.com/Zv2bBox.png

And that should be it! Sorry for not doing it myself but I didn't want to mess anything up. This will allow a fully functioning bell app on iOS user's home screen for easier access!

**Comment by nicolaschan** [comment]
Sounds good, I'll definitely implement this. Thanks for taking the time to put together the tags we need to make it work!

**Comment by nicolaschan** [comment]
I also made some icons in .svg format (and exported those to .png) so we can scale easily without losing any resolution. Feel free to use them for the Twitter profile picture. If you would like the color changed or a particular resolution, just let me know and I'll add it.

I don't have a modern iOS device, so when this commit goes live, let me know if it's working properly and then I'll close this issue.

Also worth noting that it already works for Android due to the manifest.json.

**Comment by JamsheedMistri** [comment]
@nicolaschan Awesome! Logo looks great. In fact I made them in inkscape as well but never uploaded the svg xD

Anyway the title is "Countdown" instead of "bell", contrary to what the code says ("Bell"). Since the GitHub repo is "bell" shouldn't it be called "bell" with a lowercase b? IMHO that's a bit better. Anyway up to you 👍 

Also the icon isn't working... are you sure it's linked to the correct location?

**Comment by nicolaschan** [comment]
Thanks for trying it out. This update isn't actually live yet. I'm also working on the message API thing right now so once that's done I'll push it live. I'll add another comment here when the changes are live and ready to test. (https://countdown.zone/api/version will say "3.4.0" when the change is published)

**Comment by JamsheedMistri** [comment]
Oh, my bad 😅 thanks man

**Comment by JamsheedMistri** [comment]
**Functional:**
- Icon
- Standalone app

**Issues:**
- **Name** — Name is still "Countdown" instead of "bell" — I think this might have to do with `manifest.json`, however it's not really a big issue if you want to keep it as "Countdown". If you want to keep it as Countdown, you should probably change the meta tag that you just added for iOS to that as well.
- **Status bar** — I'm not sure why it's not working as intended. [Here's a video that I recorded of what it looks like.](https://youtu.be/geSYXa027K4) If you have any ideas as to how to fix this, go ahead. I'm using [this article](https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab) for reference. If you can't fix it, we could try `default`, or `black` — IMO `default` will be better.

**Comment by nicolaschan** [comment]
Sounds like this is fixed. If not, feel free to re-open.
