### ISSUE TITLE
"Schedule Source" Covered

### ISSUE THREAD

**Issue by JamsheedMistri** [nicolaschan/bell#39]
I'm pretty sure this is an issue with the settings, unless it's intentional (why would it be)? https://i.imgur.com/EnoYNfV.png

Using bell v3.4.0

**Comment by nicolaschan** [comment]
Yep, I noticed that too. Definitely not intentional. Let's see if commit 51859936 fixes it.

**Comment by JamsheedMistri** [comment]
Fixed for me!

**Comment by nicolaschan** [comment]
Great! If anyone comes across this issue in the future, this usually happens when the list of schools isn't loading properly. https://countdown.zone/api/sources
