### ISSUE TITLE
Make notification and school message larger on mobile

### ISSUE THREAD

**Issue by JamsheedMistri** [nicolaschan/bell#40]
It might just be me, but I can barely read the notification on mobile. Same with the "Los Altos High School" that pops up at the top left.

https://i.imgur.com/6OOl59J.jpg

**Comment by nicolaschan** [comment]
See #41 since these are similar issues (mobile scaling)

**Comment by nicolaschan** [comment]
Resolving in favor of #41 to track this issue.
