### ISSUE TITLE
Extremely high cpu usage in background

### ISSUE THREAD

**Issue by niceecin** [nicolaschan/bell#65]
If I leave bell.plus open for a few days (a few hours of actual computer use) in the background while doing other things it runs the browser's cpu usage over 100% (according to top -u on macos). It seems like there's some kind of leak somewhere, but I don't really have the ability to debug where it comes from at the moment. This problem occurs in both Firefox and Google Chrome. There's a pretty slim chance the leak is somewhere else other than the site, because the cpu usage issue is resolved when I close the tab. I do not have any extensions installed.

I would recommend just double checking that the page isn't causing any issues with CPU usage, and if it isn't I guess I should do some closer monitoring of the source of the usage.

**Comment by nicolaschan** [comment]
Thanks for reporting this. Are you able to open the developer console when this happens? A screenshot of some of the performance data from it would be very useful to debug this.

**Comment by niceecin** [comment]
Hi, I haven't been able to reproduce the issue, even though it has occurred several times before (ugh). If it comes back I will make sure to get some solid debug data and get back to you then. I will close this issue for now.
