### ISSUE TITLE
Custom Schedule Enhancement

### ISSUE THREAD

**Issue by ConnorSimply** [nicolaschan/bell#66]
When selecting the day for the time block in a custom schedule there should be an option for every weekday (Mon-Fri). At our school, our bell schedule is the same every day, every week. Entering the schedule for each day might improve the ease of custom scheduling.

**Current Way**
![Capture](https://user-images.githubusercontent.com/12714889/54770113-9b29cf00-4bd0-11e9-871f-36ea879e08a6.PNG)

**Proposed Way**
![Capture](https://user-images.githubusercontent.com/12714889/54770203-c3b1c900-4bd0-11e9-9279-80126412f829.PNG)

**Comment by nicolaschan** [comment]
Great suggestion! I'll plan on adding this.
