### ISSUE TITLE
Add Standard Time option

### ISSUE THREAD

**Issue by BrewerBall** [nicolaschan/bell#80]
Hello! 

I just installed your Bell Countdown extension and am using the Custom Schedule function to help my 8 year old stay on track while doing remote learning this semester.  Since she is still learning how to tell time, I would like to see if you can add an option to select either Military Time **or** Standard AM/PM Time.

Thanks for your consideration!
Amy

**Comment by nicolaschan** [comment]
Thanks for the suggestion! Since the main timer displays time remaining, are you referring to the schedule shown on the second page when you scroll down?

**Comment by BrewerBall** [comment]
Well, it would seem I looked at this the wrong way.  I didn't realize this was the countdown to the next bell, and not the clock. Please disregard! :-)
