### ISSUE TITLE
Can this be embedded on webpage?

### ISSUE THREAD

**Issue by MrLaClair** [nicolaschan/bell#86]
We are a school who would love to embed this onto our Home webpage so that the clock feature shows up and counts down directly there rather than have our parents and students have to go completely to another tab or website.  Is this a possibility?

**Comment by nicolaschan** [comment]
Yes, you should be able to use an [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). 

```html
<iframe src="https://bell.plus/lahs">
```

but you can replace `lahs` with your school's name if it is one of the available schedules.
